spring:
  application:
    name: banking-accounts
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
  data:
    mongodb: 127.0.0.1
    host: 27017
    database: bankingAccounts
current:
  api:
    overdraft: 100000.0

